# Generated by Django 5.0.7 on 2024-08-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RestAPIapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=300)),
                ("author", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
