# Generated by Django 5.0.7 on 2024-08-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RestAPIapp", "0002_book_delete_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
