# Generated by Django 5.0.7 on 2024-08-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RestAPIapp", "0003_ModelViewSetAdded"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
